### PR TITLE
Quick copy changes

### PR DESCRIPTION
**Pull request by rjmajma**
Some quick copy changes to help with a demo.

### CODE REVIEW

**Comment by konklone** [comment]
Your changes look good. I removed a typo'ed `The` and changed `allows` to `gives` in 12a73a1. @rjmajma, if you're good with my extra changes, feel free to merge.

**Comment by konklone** [comment]
(And, once the Travis build is done.)

**Comment by rjmajma** [comment]
Way to not let me merge :hammer:, @konklone.

**Comment by konklone** [comment]
He who :hammer:'s first...:hammer:'s first.

**Pull request merged**
