### PR TITLE
Expandable help text

### PR DESCRIPTION
**Pull request by theresaanna**
I implemented a version of the first pair of mocks here: https://github.com/18F/foia-hub/issues/719. I was unable to make the gray box span the entire width of the sidebar as the structure of the sidebar's CSS doesn't allow for it. Here's what I implemented:

screen shot 2015-04-16 at 8 33 47 am

The gray box slides up/down like the banner.

### CODE REVIEW

**Comment by khandelwal** [comment]
@theresaanna Thanks for helping out with this. So much :heart:.

**Comment by khandelwal** [comment]
Fixes #719

**Comment by khandelwal** [comment]
I've added in the correct definitions to each of these. 
screen shot 2015-04-20 at 9 11 52 am

**Comment by khandelwal** [comment]
@ramirezg Will our analytics tell us when someone expands a definition, and which definition they expand?

**Comment by khandelwal** [comment]
@theresaanna 's changes look good to me. 
@rjmajma I need you to review the content, and then merge this in if you're happy.

**Comment by ramirezg** [comment]
@khandelwal No not yet, I can add the trackers in these and banner.

**Comment by khandelwal** [comment]
@ramirezg Let's do that as a separate pull request.

**Comment by ramirezg** [comment]
@khandelwal Just added the analytics to 18F/foia-hub/pull/737
@theresaanna do you mind taking a look to make sure I didn't ruin any of the js?

**Comment by ramirezg** [comment]
:+1: toggled the definitions at least 100 times while testing the analytics these work great.

**Pull request merged**
