### PR TITLE
Securing cookies

### PR DESCRIPTION
**Pull request by khandelwal**
This is based off another branch (and hence is messier than it looks). 

This sets the following settings to True: 

CSRF_COOKIE_SECURE
SESSION_COOKIE_SECURE
See: https://docs.djangoproject.com/en/1.6/howto/deployment/checklist/#https

### CODE REVIEW

**Comment by khandelwal** [comment]
fixes: #586, #587

**Comment by ramirezg** [comment]
:+1: This is ready to merge after 590

**Comment by konklone** [comment]
There's a lot of commits in here, @khandelwal, including ones that look unrelated to cookies.

**Comment by khandelwal** [comment]
Yeah, it's a branch based on a branch that wasn't merged. I've already talked to @ramirezg about it.

**Pull request merged**
