### PR TITLE
adding req. for new relic

### PR DESCRIPTION
**Pull request by ramirezg**
We should probably have this here.

### CODE REVIEW

**Comment by khandelwal** [comment]
Hmm. I don't know how to manage this - but this isn't something everyone is going to have or want. Leave it commented out?

**Comment by konklone** [comment]
I've seen people use `requirements-dev.txt` for development-only requirements (like testing libraries). We could do a `requirements-prod.txt` for production-specific stuff.

Or we could just leave it in - I think installing additional pip libraries into a virtualenv is pretty harmless.

**Comment by khandelwal** [comment]
Yeah, we have a requirements-dev.txt. Let's move this into a requirements-prod.txt.

**Comment by ramirezg** [comment]
Anything else we want to put in requirements-prod.txt while we are at it?

**Pull request merged**
