### PR TITLE
508 fixes

### PR DESCRIPTION
**Pull request by shawnbot**
:tada: **Ready to merge!** :tada: 

This PR attempts to address all of the 508 compliance tasks in #578. I've been checking off items there as I do them here. Ideally these checks would have automated tests (see #585), but we'll have to settle for doing them as a one-off for now.

Some notes:
* The `sr-only` classes are intended for classifying elements that should be *only* visible to screen readers. The `sr-only--focus` class is for elements that should be invisible until tabbed to, as in our skip navigation link. These are powered by the `sr-only` mixin, which can be used instead of the class: `@include sr-only()`.
* I've labeled the search input with the heading above it by wrapping its text in `<label for="query"></label>`, but it may be better to have a more descriptive label that's sr-only, e.g. `<label class="sr-only">Enter your search terms here</label>`

### CODE REVIEW

**Comment by nickbristow** [comment]
Absolutely. I'm pretty free. Just put something on the books.

On Tuesday, March 3, 2015, Shawn Allen <notifications@github.com> wrote:

> OK, so with the exception of color contrast (which would be better handled
> in an automated test) and aria attributes for the auto-complete input
> <https://webaccessibility.withgoogle.com/unit?unit=6&lesson=13>, this is
> ready for another once-over from @nickbristow
> <https://github.com/nickbristow>. Nick, can I get some time from you
> tomorrow to go over these?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/foia-hub/pull/591#issuecomment-77076799>.
>


-- 
Nick Bristow
18f <http://18f.gsa.gov> Innovation Specialist
Nick.Bristow@gsa.gov

**Comment by ericadeahl** [comment]
@shawnbot - suggestion was to darken the hover color, not the link text itself - is that what you did?

**Comment by ericadeahl** [comment]
@shawnbot cool just checking, thanks!

**Comment by vz3** [comment]
Looks good, merging

**Pull request merged**
