### PR TITLE
A new round of content changes

### PR DESCRIPTION
**Pull request by khandelwal**
* Implements content changes on the home page
* Removes the /learn/ page (but doesn't remove the template in case we want to bring it back from the dead)
* Implements content changes on the about page.

### CODE REVIEW

**Comment by khandelwal** [comment]
screen shot 2015-04-02 at 5 36 09 pm

**Comment by khandelwal** [comment]
screen shot 2015-04-02 at 5 36 53 pm

**Comment by khandelwal** [comment]
fixes #700 
fixes #699 
fixes #697

**Comment by rjmajma** [comment]
#ticketslayer

**Comment by nsinai** [comment]
Looks awesome!  Will there be a preview of future features?  Maybe "Future Features"?  :)

**Pull request merged**
