### PR TITLE
Visual glitches

### PR DESCRIPTION
**Pull request by vz3**

### CODE REVIEW

**Comment by vz3** [comment]
Outstanding: Small search box, implementation of glyphs for home page process list, sticky footer, full alphabet on index
screen shot 2015-03-02 at 8 17 03 pm
screen shot 2015-03-02 at 8 17 17 pm
screen shot 2015-03-02 at 8 17 54 pm
screen shot 2015-03-02 at 8 18 06 pm

**Comment by vz3** [comment]
uhh no idea why the test failed

**Comment by vz3** [comment]
With commit 2901162 this should pass and be ready to go.

**Comment by khandelwal** [comment]
@shawnbot Will you review and merge this?

**Comment by khandelwal** [comment]
I've changed the threshold for build failures. This is ready for review, and safely merge when it's ready.

**Pull request merged**
