### PR TITLE
Redesign: Sitewide elements, typography, home page implementation

### PR DESCRIPTION
**Pull request by vz3**
# Redesign

This pull request implements the sitewide elements including alpha+US Gov banner, top nav, footer, new typography and colors throughout, a new header em style for underlined headers, and Bourbon Bitters for styling.

# Views

## Homepage Large
screen shot 2015-01-20 at 9 04 32 am

## Homepage Medium
screen shot 2015-01-20 at 9 24 36 am

## Homepage Small
screen shot 2015-01-20 at 9 24 45 am

# Notes

This uses a TypeKit version of Proxima Nova, the main typeface for FOIAHub. We should move the font hosting to 18F servers for the final product. IE support is not implemented yet.

### CODE REVIEW

**Comment by vz3** [comment]
This is ready for review.

**Comment by khandelwal** [comment]
Fantastic! @theresaanna will you take a look at this pull request?

**Comment by rjmajma** [comment]
Related to #391.

**Comment by vz3** [comment]
Implements #392 #395

**Pull request merged**
