### PR TITLE
removing foia-hub forms from profile

### PR DESCRIPTION
**Pull request by ramirezg**
related to 18F/foia-hub/issues/521

### CODE REVIEW

**Comment by khandelwal** [comment]
Is there a reason we shouldn't simply set show_webform to False in production?

**Comment by ramirezg** [comment]
I think it is [False](https://github.com/18F/foia-hub/blob/master/foia_hub/settings/production.py)

**Comment by khandelwal** [comment]
Have you confirmed that we're using the production settings on the server?

**Comment by ramirezg** [comment]
The fabfile shows that it should be using the [production settings](https://github.com/18F/foia-hub/blob/master/fabfile.py#L5)

**Pull request closed without merging**
