### PR TITLE
Updated License

### PR DESCRIPTION
**Pull request by rjmajma**
License now includes Postgres, Django, and Node. Please check this out and make sure we're not missing other things. Please give this a look @konklone.

### CODE REVIEW

**Comment by rjmajma** [comment]
This hopefully fixes #418.

**Comment by cmc333333** [comment]
I don't think this is necessary -- this repository doesn't distribute any of those libraries/applications. It *does* distribute some node libraries, though.

**Comment by khandelwal** [comment]
+1 We don't need to include Django or Postgres. @cmc333333 Are you suggesting we remove the Node thing too, in lieu of something else?

**Comment by konklone** [comment]
Right, the two directories which have libraries we need to download are:

* https://github.com/18F/foia-hub/tree/master/foia_hub/static
* https://github.com/18F/foia-hub/tree/master/node_modules

I'd be up for getting rid of the `node_modules` directory and having that be installed on demand, we'd just have to make sure the webhook workflow expects that.

**Comment by cmc333333** [comment]
+1 @konklone . In addition to removing the license concern, you get to cut down the lines of code!

The big gotcha is that, even if you've remove all the library sources from the repo, if you're distributing a minified/compiled JS or CSS file, it'll no doubt include those dev-loaded libraries. This triggers the redistribution clause in GPL/MIT, etc.

**Comment by konklone** [comment]
I think it's also safe for us to link to the license, rather than distribute the full text for each one. At least, that's the overwhelming community practice.

I've assigned myself the PR, and will update it with our conclusions as part of this sprint.

**Comment by konklone** [comment]
OK, I removed node_modules, added a `package.json` to the `deploy/` subdirectory, and made it so the dependencies are installed during the deploy process. The webhook does require those node_modules be there, so they must be installed during deploy, or the webhook cannot be stopped/started.

I temporarily deployed this branch to the staging server, and used a [trivial direct-to-master commit](https://github.com/18F/foia-hub/commit/764b1add48e911d4846975b60f5f2e255b177afc) to make sure the webhook worked with the new setup, which it does.

I then [rewrote the LICENSE.md file](https://github.com/18F/foia-hub/blob/d3dd0d53c66025e39ce473d1466dc7f62e48f48b/LICENSE.md) to reference the remaining libraries we incorporate. I modeled it after the exceptions I added to the [license for the DAP dashboard](https://github.com/GSA/analytics.usa.gov/blob/master/LICENSE.md).

I think we can get rid pure, and pickadate, if we're not caring about the request form. But they're in there.

**Comment by konklone** [comment]
I've unassigned myself from the PR, and am looking for someone to review and wield the merge :hammer:.

**Comment by khandelwal** [comment]
Do we need to add to the instructions on README? Does something change in development if we're removing these modules? (I'm assuming something would need to be installed?)

**Comment by konklone** [comment]
@khandelwal Nothing about the normal dev or deployment process as it affects the developer/user changed.

If you were running the webhook server locally in development for some reason, you'd have to do `npm install` instead of the individual dependencies -- I just updated the `deploy/README.md` file in https://github.com/18F/foia-hub/commit/fd488e63376fc21a8972d28047957f56404a428e to take care of that.

**Pull request merged**
