### PR TITLE
Form design

### PR DESCRIPTION
**Pull request by vz3**
Styling forms, now compatible w Parsley. Currently only implemented for centralized agencies.

### CODE REVIEW

**Comment by ramirezg** [comment]
The red text only pops up on parsley-pattern, but not parsley-required for me. 

screen shot 2015-06-08 at 5 01 03 pm
screen shot 2015-06-08 at 5 00 51 pm

**Comment by vz3** [comment]
thanks. looks like font-awesome glyph isn't showing up either.

**Comment by vz3** [comment]
@ramirezg check again?

**Comment by ramirezg** [comment]
@vz3 :+1: it's working for me now. I've updated the required fields based on the csv, but I think the labels might not match up.

**Pull request merged**
